apiVersion: v1
kind: Service
metadata:
  name: tensorboard-hyperparam-sweep
  labels:
    name: tensorboard-hyperparam-sweep
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard-hyperparam-sweep
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tensorboard-hyperparam-sweep
  name: tensorboard-hyperparam-sweep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard-hyperparam-sweep
  template:
    metadata:
      labels:
        app: tensorboard-hyperparam-sweep
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: chzbrgr71/tensorboard:1.8
          args:                
            - "--logdir"
            - "/tf-output/training_summaries"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tf-output
              subPath: tfjob-retrain-edsheeran
              name: azure-files
          ports:
            - containerPort: 6006
              protocol: TCP