tfjob:
  name: tfjob-hyperparam-sweep
  useGPU: true

container:
  image: briar.azurecr.io/chzbrgr71/image-retrain:1.8-gpu
  pvcName: azure-files

hyperParamValues:
  learning_rate:
    - 0.001
    - 0.01
    - 1.0
  train_batch_size:
    - 50
    - 100
