tfjob:
  name: tfjob-hyperparam-sweep
  useGPU: true

container:
  image: briaracr.azurecr.io/chzbrgr71/image-retrain:2.0-gpu
  pvcName: pvc-azure-files-dynamic
  subPath: tfjob-image-training

hyperParamValues:
  learning_rate:
    - 0.001
    - 0.01
    - 1.0
  train_batch_size:
    - 50
    - 100
