apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: {{.Values.tfjob.name}}
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          volumes:
            - name: azure-files
              persistentVolumeClaim:
                claimName: azure-files
          containers:
          - image: {{.Values.container.image}}:{{.Values.container.imageTag}}
            name: tensorflow
            args:                
            - "--bottleneck_dir=bottlenecks"
            - "--model_dir=/tmp/tensorflow/tf-output/inception"
            - "--summaries_dir=/tmp/tensorflow/tf-output/training_summaries/baseline"
            - "--output_graph=/tmp/tensorflow/tf-output/retrained_graph.pb"
            - "--output_labels=/tmp/tensorflow/tf-output/retrained_labels.txt"
            - "--image_dir=images"        
            imagePullPolicy: Always
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
              - mountPath: /tmp/tensorflow
                subPath: {{.Values.tfjob.name}}
                name: azure-files
          restartPolicy: OnFailure
    WORKER:
      replicas: {{.Values.training.workercount}}
      template:
        spec:
          volumes:
            - name: azure-files
              persistentVolumeClaim:
                claimName: azure-files
          containers:
          - image: {{.Values.container.image}}:{{.Values.container.imageTag}}
            name: tensorflow
            args:                
            - "--image_dir=images"        
            imagePullPolicy: Always
            resources:
              limits:
                nvidia.com/gpu: 1
          restartPolicy: OnFailure
    PS:
      replicas: 1
      template:
        spec:
          containers:
          - image: {{.Values.container.image}}:{{.Values.container.imageTag}}
            name: tensorflow
            args:                
            - "--image_dir=images"        
            imagePullPolicy: Always
          restartPolicy: OnFailure