tfjob:
  name: tfjob-image-training
  
container:
  image: briaracr.azurecr.io/chzbrgr71/image-retrain
  imageTag: 2.1-gpu
  pvcName: pvc-azure-files-dynamic
  subPath: tfjob-image-training

training:
  randomcrop: 5
  randomscale: 5
  randombrightness: 5
  learningrate: 0.01
  trainingbatchsize: 100 
