apiVersion: v1
kind: Service
metadata:
  name: tensorboard-image-retraining
  labels:
    name: tensorboard-image-retraining
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard-image-retraining
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tensorboard-image-retraining
  name: tensorboard-image-retraining
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard-image-retraining
  template:
    metadata:
      labels:
        app: tensorboard-image-retraining
    spec:
      volumes:
        - name: tf-azure-disk
          persistentVolumeClaim:
            claimName: tf-azure-disk
      containers:
        - name: tensorflow
          image: chzbrgr71/tensorboard:1.6
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /model
              name: tf-azure-disk
          ports:
            - containerPort: 6006
              protocol: TCP