apiVersion: v1
kind: Service
metadata:
  name: tfjob-distributed-tensorboard
  labels:
    name: tfjob-distributed-tensorboard
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tfjob-distributed-tensorboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tfjob-distributed-tensorboard
  name: tfjob-distributed-tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfjob-distributed-tensorboard
  template:
    metadata:
      labels:
        app: tfjob-distributed-tensorboard
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: briaracreu.azurecr.io/tensorflow/tensorflow:1.9.0
          command:
          - /usr/local/bin/tensorboard
          args:
          - --logdir
          - /tmp/tensorflow
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp/tensorflow
              subPath: tfjob-dist-brian
              name: azure-files
          ports:
            - containerPort: 6006
              protocol: TCP