apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-retrain-pets
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-standard
  resources:
    requests:
      storage: 8Gi
---
apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: tfjob-retrain-pets
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            - image: chzbrgr71/image-retrain:1.8-pets-gpu
              name: tensorflow
              args:                
                - "--bottleneck_dir=/tf-output/bottlenecks"
                - "--model_dir=/tf-output/inception"
                - "--summaries_dir=/tf-output/training_summaries/baseline"
                - "--output_graph=/tf-output/retrained_graph.pb"
                - "--output_labels=/tf-output/retrained_labels.txt"
                - "--image_dir=images"        
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: disk-retrain-pets
                  mountPath: /tf-output
          restartPolicy: OnFailure
          volumes:
            - name: disk-retrain-pets
              persistentVolumeClaim:
                claimName: disk-retrain-pets