apiVersion: v1
kind: Service
metadata:
  name: tfjob-distributed-azfile-tensorboard
  labels:
    name: tfjob-distributed-azfile-tensorboard
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tfjob-distributed-azfile-tensorboard
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tfjob-distributed-azfile-tensorboard
  name: tfjob-distributed-azfile-tensorboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfjob-distributed-azfile-tensorboard
  template:
    metadata:
      labels:
        app: tfjob-distributed-azfile-tensorboard
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: chzbrgr71/tensorboard:1.8
          args:                
            - "--logdir"
            - "/tmp/edsheeran-dist/logs"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tmp
              name: azure-files
          ports:
            - containerPort: 6006
              protocol: TCP