apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tf-azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-standard
  resources:
    requests:
      storage: 8Gi
---
apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: tf-image-retraining-disk
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            - image: chzbrgr71/image-retrain:1.6-gpu
              name: tensorflow
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: tf-azure-disk
                  mountPath: /model
          restartPolicy: OnFailure
          volumes:
            - name: tf-azure-disk
              persistentVolumeClaim:
                claimName: tf-azure-disk