apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: tf-image-retraining
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            - image: chzbrgr71/image-retrain:1.7-gpu
              name: tensorflow
              args:                
                - "--bottleneck_dir=/tf-output/bottlenecks"
                - "--model_dir=/tf-output/inception"
                - "--summaries_dir=/tf-logs/training_summaries/long"
                - "--output_graph=/tf-output/retrained_graph.pb"
                - "--output_labels=/tf-output/retrained_labels.txt"
                - "--image_dir=images"                
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: azure-managed-disk
                  mountPath: /tf-output
                - name: azure-files
                  subPath: tf-image-retraining                
                  mountPath: /tf-logs
          restartPolicy: OnFailure
          volumes:
            - name: azure-files
              persistentVolumeClaim:
                claimName: azure-files
            - name: azure-managed-disk
              persistentVolumeClaim:
                claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard-image-retraining
  labels:
    name: tensorboard-image-retraining
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard-image-retraining
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tensorboard-image-retraining
  name: tensorboard-image-retraining
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard-image-retraining
  template:
    metadata:
      labels:
        app: tensorboard-image-retraining
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: chzbrgr71/tensorboard:1.7
          args:                
            - "--logdir"
            - "/tf-logs/tf-image-retraining/training_summaries"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /tf-logs
              name: azure-files
          ports:
            - containerPort: 6006
              protocol: TCP