apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: tf-image-retraining
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            - image: chzbrgr71/image-retrain:1.5-gpu
              name: tensorflow
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: azure-managed-disk
                  mountPath: /tmp/tensorflow
                - name: azure-files
                  subPath: tf-image-retraining                
                  mountPath: /tf-output
          restartPolicy: OnFailure
          volumes:
            - name: azure-files
              persistentVolumeClaim:
                claimName: azure-files
            - name: azure-managed-disk
              persistentVolumeClaim:
                claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard-image-retraining
  labels:
    name: tensorboard-image-retraining
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 6006
  selector:
    app: tensorboard-image-retraining
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: tensorboard-image-retraining
  name: tensorboard-image-retraining
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorboard-image-retraining
  template:
    metadata:
      labels:
        app: tensorboard-image-retraining
    spec:
      volumes:
        - name: azure-files
          persistentVolumeClaim:
            claimName: azure-files
      containers:
        - name: tensorflow
          image: tensorflow/tensorflow:1.10.0
          imagePullPolicy: Always
          command:
            - /usr/local/bin/tensorboard
          args:
            - --logdir
            - /tf-output/training_summaries
          volumeMounts:
            - mountPath: /tf-output
              subPath: tf-image-retraining
              name: azure-files
          ports:
            - containerPort: 6006
              protocol: TCP