apiVersion: kubeflow.org/v1alpha2
kind: TFJob
metadata:
  name: tf-image-retraining-disk
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        spec:
          containers:
            - image: chzbrgr71/image-retrain:1.7-gpu
              name: tensorflow
              args:                
                - "--bottleneck_dir=/tf-output/bottlenecks"
                - "--model_dir=/tf-output/inception"
                - "--summaries_dir=/tf-output/training_summaries/long"
                - "--output_graph=/tf-output/retrained_graph.pb"
                - "--output_labels=/tf-output/retrained_labels.txt"
                - "--image_dir=images"        
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - name: azure-managed-disk
                  mountPath: /tf-output
          restartPolicy: OnFailure
          volumes:
            - name: azure-managed-disk
              persistentVolumeClaim:
                claimName: azure-managed-disk